from flask import Blueprint, request, jsonify
from ..models.user import User, UserProfile, UserRole
from ..utils.id_utils import generate_prefixed_id
from .. import db, jwt
from flask_jwt_extended import create_access_token, jwt_required, get_jwt_identity
import datetime

auth_bp = Blueprint('auth_bp', __name__)

@auth_bp.route('/register', methods=['POST'])
def register():
    data = request.get_json()
    email = data.get('email')
    password = data.get('password')
    first_name = data.get('firstName')
    last_name = data.get('lastName')
    role = data.get('role', UserRole.CUSTOMER) # Default to customer

    if not email or not password:
        return jsonify({"msg": "Email and password are required"}), 400

    if User.query.filter_by(email=email).first():
        return jsonify({"msg": "Email already exists"}), 409 # Conflict

    try:
        new_user = User(email=email, role=role)
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.flush() # Flush to get new_user.id if it's generated by DB or for relationships

        # Create UserProfile
        new_profile = UserProfile(
            user_id=new_user.id,
            first_name=first_name,
            last_name=last_name
        )

        # Generate prefixed IDs based on role or general user status
        # This logic can be expanded. For now, a generic USR_ID for all, and CST_ID for customers.
        new_profile.usr_id = generate_prefixed_id("USR") # All users get a USR ID

        if role == UserRole.CUSTOMER:
            new_profile.cst_id = generate_prefixed_id("CST")
        elif role == UserRole.VENDOR:
            new_profile.vnd_id = generate_prefixed_id("VND")
        # Add other role-specific ID generations here (SCH, LND, etc.)

        db.session.add(new_profile)
        db.session.commit()

        # Prepare user data for response (excluding password)
        user_data = {
            "id": new_user.id,
            "email": new_user.email,
            "role": new_user.role,
            "firstName": new_profile.first_name,
            "lastName": new_profile.last_name,
            "usr_id": new_profile.usr_id,
            "cst_id": new_profile.cst_id if role == UserRole.CUSTOMER else None,
            "vnd_id": new_profile.vnd_id if role == UserRole.VENDOR else None,
        }

        return jsonify({"msg": "User registered successfully", "user": user_data}), 201

    except Exception as e:
        db.session.rollback()
        # Log the error e
        print(f"Error during registration: {e}")
        return jsonify({"msg": "An error occurred during registration.", "error": str(e)}), 500


@auth_bp.route('/login', methods=['POST'])
def login():
    data = request.get_json()
    email = data.get('email')
    password = data.get('password')

    if not email or not password:
        return jsonify({"msg": "Email and password are required"}), 400

    user = User.query.filter_by(email=email).first()

    if user and user.check_password(password):
        # Fetch profile to include in JWT or response
        profile = UserProfile.query.filter_by(user_id=user.id).first()

        # Identity for JWT can be user.id or a dictionary of claims
        # Including role in the token can be useful for frontend role-based rendering
        # and for backend @jwt_required decorated routes if we add custom claims
        identity_data = {
            "id": user.id,
            "email": user.email,
            "role": user.role,
            "usr_id": profile.usr_id if profile else None
        }

        # Consider token expiration time
        # expires_delta = datetime.timedelta(days=1) # Example: token valid for 1 day
        # access_token = create_access_token(identity=identity_data, expires_delta=expires_delta)
        access_token = create_access_token(identity=identity_data)

        user_data_for_response = {
            "id": user.id,
            "email": user.email,
            "role": user.role,
            "firstName": profile.first_name if profile else None,
            "lastName": profile.last_name if profile else None,
            "usr_id": profile.usr_id if profile else None,
            "cst_id": profile.cst_id if profile and user.role == UserRole.CUSTOMER else None,
            "vnd_id": profile.vnd_id if profile and user.role == UserRole.VENDOR else None,
        }
        return jsonify(access_token=access_token, user=user_data_for_response), 200
    else:
        return jsonify({"msg": "Invalid email or password"}), 401

# Example of a protected route
@auth_bp.route('/profile', methods=['GET'])
@jwt_required()
def protected_profile():
    current_user_identity = get_jwt_identity() # This will be the dictionary we set in create_access_token
    user_id = current_user_identity['id']

    user = User.query.get(user_id)
    if not user:
        return jsonify({"msg": "User not found"}), 404

    profile = UserProfile.query.filter_by(user_id=user.id).first()
    if not profile:
        return jsonify({"msg": "Profile not found for user"}), 404

    user_data = {
        "id": user.id,
        "email": user.email,
        "role": user.role,
        "firstName": profile.first_name,
        "lastName": profile.last_name,
        "phone_number": profile.phone_number,
        "usr_id": profile.usr_id,
        "cst_id": profile.cst_id,
        "vnd_id": profile.vnd_id,
        "sch_id": profile.sch_id,
        "lnd_id": profile.lnd_id,
        "created_at": user.created_at.isoformat(),
        "profile_updated_at": profile.updated_at.isoformat()
    }
    return jsonify(user=user_data), 200


# Callback for customizing token claims (optional)
# @jwt.user_claims_loader
# def add_claims_to_access_token(identity):
#     # `identity` is what we passed to `create_access_token`
#     # We can fetch more user data and add it to the token
#     # For example, if identity is just user_id:
#     # user = User.query.get(identity)
#     # return {"role": user.role, "email": user.email}
#     # If identity is already a dict as we made it:
#     return {"role": identity.get("role")}


# Callback for checking if a token is revoked (optional, requires a token blacklist)
# @jwt.token_in_blocklist_loader
# def check_if_token_in_blocklist(jwt_header, jwt_payload):
#     jti = jwt_payload["jti"]
#     # Check if jti is in your database of revoked tokens
#     # return TokenBlocklist.is_jti_blacklisted(jti)
#     return False # For now, no blocklist

# Standard error handlers for JWT (optional, but good for consistent API responses)
@jwt.expired_token_loader
def expired_token_callback(jwt_header, jwt_payload):
    return jsonify({"msg": "Token has expired"}), 401

@jwt.invalid_token_loader
def invalid_token_callback(error_string):
    return jsonify({"msg": "Invalid token", "error": error_string}), 422 # Unprocessable Entity

@jwt.unauthorized_loader
def missing_token_callback(error_string):
    return jsonify({"msg": "Authorization token is missing", "error": error_string}), 401
